# Railway-specific deployment configuration

[build]
provider = "docker"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
startCommand = "python src/lightweight_discord_bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = [
    "USE_GOOGLE_DRIVE=false",
    "SYNC_ON_BOOT=false", 
    "ENVIRONMENT=production",
    "DEPLOY_ENV=railway",
    "PYTHONUNBUFFERED=1"
]
