# Railway-specific deployment configuration

[build]
provider = "docker"
dockerfilePath = "Dockerfile.full"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = [
    "USE_GOOGLE_DRIVE=true",
    "SYNC_ON_BOOT=true", 
    "ENVIRONMENT=production",
    "DEPLOY_ENV=railway",
    "PYTHONUNBUFFERED=1",
    "FORCE_REAL_MODULES=true",
    "PYTHONPATH=/app:/app/src",
    "TRADING_ENABLED=true",
    "LIVE_TRADING=true"
]
