version: "3.8"

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: money_printer_scraper
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    command: python data_scraper.py